### ISSUE TITLE
using rn.json returns error

### ISSUE THREAD

**Issue by tiero** [singnet/reputation-simulation#4]
After cloning and installing the reputation-simulation, I run:
`python3 snsim/reputation_simulation/ReputationSim.py snsim/rn.json`

This what happens here:

```
/Users/tiero/projects/snet/reputation-simulation
Traceback (most recent call last):
  File "snsim/reputation_simulation/ReputationSim.py", line 912, in <module>
    main()
  File "snsim/reputation_simulation/ReputationSim.py", line 902, in main
    runner.call(config['batch']['parameter_combinations'], config,rs=rs)
  File "snsim/reputation_simulation/ReputationSim.py", line 826, in call
    self.set_param(myconfigfile, setting)
  File "snsim/reputation_simulation/ReputationSim.py", line 809, in set_param
    nextKey = next(iter(new_val.items()))[0]
AttributeError: 'str' object has no attribute 'items'
```

**Comment by deborahduong** [comment]
Hi, I changed the config so as to be able to include more kinds of runs in the batch like SOM and TOM that have more than one parameter change that characterizes them.   I just put in a new config file to use with the new setup, debugRn.json.  Please use that one.  There is a problem with halfTenth that I am debugging now.

**Comment by tiero** [comment]
@deborahduong the correct one to use is `snsim/debugRn.json` ?

**Comment by tiero** [comment]
All works now, thanks!

**Comment by deborahduong** [comment]
yes, still debugging the halfTenth
